version: '3'
services:
  client:
    image: react:latest
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
  ipfs:
    image: jbenet/go-ipfs:latest
    ports:
      - "8080:8080"
      - "4001:4001"
      - "127.0.0.1:5001:5001"
